// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9ONo6f3PUE0hTlpXJwRyBc7XuhwgGhU',
    appId: '1:824815511288:web:f09d29f4e2a4a6d17e7d0d',
    messagingSenderId: '824815511288',
    projectId: 'chat-app1-83b6a',
    authDomain: 'chat-app1-83b6a.firebaseapp.com',
    storageBucket: 'chat-app1-83b6a.firebasestorage.app',
    measurementId: 'G-BYX0SD0798',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjXNKu1IX19IczLWKFE3Zgf_YVRMD2r9w',
    appId: '1:824815511288:android:89a5f9bb473c257d7e7d0d',
    messagingSenderId: '824815511288',
    projectId: 'chat-app1-83b6a',
    storageBucket: 'chat-app1-83b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3EU-OhXiLe_csA6ViazFUXTPbiOz_a1o',
    appId: '1:824815511288:ios:b5cdd78cd16a8fd17e7d0d',
    messagingSenderId: '824815511288',
    projectId: 'chat-app1-83b6a',
    storageBucket: 'chat-app1-83b6a.firebasestorage.app',
    iosBundleId: 'com.example.chatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3EU-OhXiLe_csA6ViazFUXTPbiOz_a1o',
    appId: '1:824815511288:ios:b5cdd78cd16a8fd17e7d0d',
    messagingSenderId: '824815511288',
    projectId: 'chat-app1-83b6a',
    storageBucket: 'chat-app1-83b6a.firebasestorage.app',
    iosBundleId: 'com.example.chatt',
  );

}